import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";

//Outfit font configuration
const outfit = Outfit({
  subsets: ["latin"],
  display: "swap", // Prevents layout shift
  variable: "--font-outfit", // Define a CSS variable name for use in CSS/Tailwind
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${outfit.className} antialiased`}>{children}</body>
    </html>
  );
}
